### ISSUE TITLE
io_preview.dart

### ISSUE THREAD

**Issue by smocken78** [shubham16g/multi_image_picker_view#44]
Hi, 
inside the io_preview.dart in line 31:

`
Uri.tryParse(imageFile.path!)?.scheme.startsWith('http') == true
          ? Image.network(
              imageFile.path!,
              fit: fit,
              errorBuilder: errorBuilder ?? _defaultErrorBuilder,
            )
          : Image.file(
              File(imageFile.path!),
              fit: fit,
              errorBuilder: errorBuilder ?? _defaultErrorBuilder,
            ),
`

should be changed to something like that: 

`
imageFile.path != null
          ? Uri.tryParse(imageFile.path!)?.scheme.startsWith('http') == true
              ? Image.network(
                  imageFile.path!,
                  fit: fit,
                  errorBuilder: errorBuilder ?? _defaultErrorBuilder,
                )
              : Image.file(
                  File(imageFile.path!),
                  fit: fit,
                  errorBuilder: errorBuilder ?? _defaultErrorBuilder,
                )
          : Image.memory(
              imageFile.bytes!,
              fit: fit,
              errorBuilder: errorBuilder ?? _defaultErrorBuilder,
            ),
`

as path maybe null.

**Comment by shubham16g** [comment]
Resolved in 2.0.0
