### ISSUE TITLE
errror running app using this multi_image_picker_view: ^1.1.0 using 

### ISSUE THREAD

**Issue by sunilsinghchaudhary00** [shubham16g/multi_image_picker_view#49]
../../../.pub-cache/hosted/pub.dev/multi_image_picker_view-1.1.0/lib/src/multi_image_picker_view.dart:114:68: Error: The argument type 'List<ImageFile>' can't be assigned to the parameter type 'List<Never>'.
 - 'List' is from 'dart:core'.
 - 'ImageFile' is from 'package:multi_image_picker_view/src/image_file.dart' ('../../../.pub-cache/hosted/pub.dev/multi_image_picker_view-1.1.0/lib/src/image_file.dart').
          final newList = reOrderCallback(widget.controller.images.toList());
                                                                   ^
Target kernel_snapshot_program failed: Exception
2

FAILURE: Build failed with an exception.

**Comment by anchao-lu** [comment]
Same issue

**Comment by sunilsinghchaudhary00** [comment]
hi for now i am using  

` multi_image_picker_view: 1.0.2 `

and it is working fine i downgraded the version 

don't add ^ it will work for now in future lets see it is fixed or not

**Comment by evan8133** [comment]
check the newest pull request i have made, i have fixed the issue, u can fork the repo and make same changes as mine

**Comment by sunil-singh-chaudhary** [comment]
can you update the pub.dev too pls

**Comment by shubham16g** [comment]
`flutter_reorderable_grid_view` 's latest version `5.4.0` have some breaking changes. But it is recommended not to introduce any breaking changes in same base version, in this case `5.*.*`.  Currently `multi_image_picker_view` is using it's version: `5.0.1`, but when someone adds `multi_image_picker_view` to their project, it uses the latest version of `flutter_reorderable_grid_view` with base version `5.*.*`. You can check in `pubspec.lock` file that the version of `flutter_reorderable_grid_view` is set to `5.4.0` even if `multi_image_picker_view` is set to use `5.0.1`.
